main: com.pixlcore.main.Main
name: PixlCore
version: 1.0.0
api-version: 1.17
author: PixlBrosGamingYT
description: Core plugin
commands:
   rename:
      description: Rename item
      usage: /rename <name>
      permission: pixlcore.rename
      permissionmessage: Nope.
   invsee:
      description: invsee
      usage: /invsee <player>
      permission: pixlcore.invsee
      permissionmessage: Nope.
   discord:
      description: Join our discord!
      usage: /discord
   spawn:
      description: Teleport to spawn
      usage: /spawn
   setspawn:
      description: Set new spawn
      usage: /setspawn
      permission: pixlcore.setspawn
      permissionmessage: Nope.
   warps:
      description: List warps
      usage: /warps
   warp:
      description: Teleport to a warp
      usage: /warp <warp name>
   setwarp:
      description: Set new warp location
      usage: /setwarp <warp name>
      permission: pixlcore.setwarp
      permissionmessage: Nope.
   back:
      description: Teleport to last location
      usage: /back